name: Build Binary

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create GitHub Release?"
        required: true
        type: boolean
        default: false
      tag:
        description: "Release tag (for release with version) (eg. v1.x)"
        required: false
        type: string

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --name "PCSX2 Texture Randomizer" --clean --specpath "./build" --distpath "./dist" --workpath "./build" --onefile bin/main.py

      - name: Rename binary for platform
        shell: bash
        run: |
          cd dist
          if [ "${{ runner.os }}" = "Windows" ]; then
            mv "PCSX2 Texture Randomizer.exe" "PCSX2-Texture-Randomizer-windows.exe"
          else
            mv "PCSX2 Texture Randomizer" "PCSX2-Texture-Randomizer-linux"
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: PCSX2-Texture-Randomizer-${{ matrix.os }}
          path: dist/PCSX2-Texture-Randomizer-*
          retention-days: 1

      - name: Upload to GitHub Release
        if: inputs.create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          files: dist/PCSX2-Texture-Randomizer-*
          generate_release_notes: true
